#define IN_STG_CODE 0

/*
 * We need offsets of profiled things...
 * better be careful that this doesn't
 * affect the offsets of anything else.
 */

#define PROFILING
#define THREADED_RTS

#include "PosixSource.h"
#include "Rts.h"
#include "Stable.h"
#include "Capability.h"

#include <inttypes.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

#define FIELD_SIZE(s_type, field) ((size_t)sizeof(((s_type*)0)->field))
#define TYPE_SIZE(type) (sizeof(type))
#define FUN_OFFSET(sym) (offsetof(Capability,f.sym) - offsetof(Capability,r))

#pragma GCC poison sizeof
char derivedConstantSTD_HDR_SIZE[1 + sizeofW(StgHeader) - sizeofW(StgProfHeader)];
char derivedConstantPROF_HDR_SIZE[1 + sizeofW(StgProfHeader)];
char derivedConstantBLOCK_SIZE[1 + BLOCK_SIZE];
char derivedConstantMBLOCK_SIZE[1 + MBLOCK_SIZE];
char derivedConstantBLOCKS_PER_MBLOCK[1 + BLOCKS_PER_MBLOCK];
char derivedConstantOFFSET_StgRegTable_rR1[1 + offsetof(StgRegTable, rR1)];
char derivedConstantOFFSET_StgRegTable_rR2[1 + offsetof(StgRegTable, rR2)];
char derivedConstantOFFSET_StgRegTable_rR3[1 + offsetof(StgRegTable, rR3)];
char derivedConstantOFFSET_StgRegTable_rR4[1 + offsetof(StgRegTable, rR4)];
char derivedConstantOFFSET_StgRegTable_rR5[1 + offsetof(StgRegTable, rR5)];
char derivedConstantOFFSET_StgRegTable_rR6[1 + offsetof(StgRegTable, rR6)];
char derivedConstantOFFSET_StgRegTable_rR7[1 + offsetof(StgRegTable, rR7)];
char derivedConstantOFFSET_StgRegTable_rR8[1 + offsetof(StgRegTable, rR8)];
char derivedConstantOFFSET_StgRegTable_rR9[1 + offsetof(StgRegTable, rR9)];
char derivedConstantOFFSET_StgRegTable_rR10[1 + offsetof(StgRegTable, rR10)];
char derivedConstantOFFSET_StgRegTable_rF1[1 + offsetof(StgRegTable, rF1)];
char derivedConstantOFFSET_StgRegTable_rF2[1 + offsetof(StgRegTable, rF2)];
char derivedConstantOFFSET_StgRegTable_rF3[1 + offsetof(StgRegTable, rF3)];
char derivedConstantOFFSET_StgRegTable_rF4[1 + offsetof(StgRegTable, rF4)];
char derivedConstantOFFSET_StgRegTable_rF5[1 + offsetof(StgRegTable, rF5)];
char derivedConstantOFFSET_StgRegTable_rF6[1 + offsetof(StgRegTable, rF6)];
char derivedConstantOFFSET_StgRegTable_rD1[1 + offsetof(StgRegTable, rD1)];
char derivedConstantOFFSET_StgRegTable_rD2[1 + offsetof(StgRegTable, rD2)];
char derivedConstantOFFSET_StgRegTable_rD3[1 + offsetof(StgRegTable, rD3)];
char derivedConstantOFFSET_StgRegTable_rD4[1 + offsetof(StgRegTable, rD4)];
char derivedConstantOFFSET_StgRegTable_rD5[1 + offsetof(StgRegTable, rD5)];
char derivedConstantOFFSET_StgRegTable_rD6[1 + offsetof(StgRegTable, rD6)];
char derivedConstantOFFSET_StgRegTable_rXMM1[1 + offsetof(StgRegTable, rXMM1)];
char derivedConstantOFFSET_StgRegTable_rXMM2[1 + offsetof(StgRegTable, rXMM2)];
char derivedConstantOFFSET_StgRegTable_rXMM3[1 + offsetof(StgRegTable, rXMM3)];
char derivedConstantOFFSET_StgRegTable_rXMM4[1 + offsetof(StgRegTable, rXMM4)];
char derivedConstantOFFSET_StgRegTable_rXMM5[1 + offsetof(StgRegTable, rXMM5)];
char derivedConstantOFFSET_StgRegTable_rXMM6[1 + offsetof(StgRegTable, rXMM6)];
char derivedConstantOFFSET_StgRegTable_rL1[1 + offsetof(StgRegTable, rL1)];
char derivedConstantOFFSET_StgRegTable_rSp[1 + offsetof(StgRegTable, rSp)];
char derivedConstantOFFSET_StgRegTable_rSpLim[1 + offsetof(StgRegTable, rSpLim)];
char derivedConstantOFFSET_StgRegTable_rHp[1 + offsetof(StgRegTable, rHp)];
char derivedConstantOFFSET_StgRegTable_rHpLim[1 + offsetof(StgRegTable, rHpLim)];
char derivedConstantOFFSET_StgRegTable_rCCCS[1 + offsetof(StgRegTable, rCCCS)];
char derivedConstantOFFSET_StgRegTable_rCurrentTSO[1 + offsetof(StgRegTable, rCurrentTSO)];
char derivedConstantOFFSET_StgRegTable_rCurrentNursery[1 + offsetof(StgRegTable, rCurrentNursery)];
char derivedConstantOFFSET_StgRegTable_rHpAlloc[1 + offsetof(StgRegTable, rHpAlloc)];
char derivedConstantOFFSET_StgRegTable_rRet[1 + offsetof(StgRegTable, rRet)];
char derivedConstantREP_StgRegTable_rRet[1 + FIELD_SIZE(StgRegTable, rRet)];
char derivedConstantOFFSET_StgRegTable_rNursery[1 + offsetof(StgRegTable, rNursery)];
char derivedConstantREP_StgRegTable_rNursery[1 + FIELD_SIZE(StgRegTable, rNursery)];
char derivedConstantOFFSET_stgEagerBlackholeInfoMag[1 + ((intptr_t)(FUN_OFFSET(stgEagerBlackholeInfo)) >= 0 ? (FUN_OFFSET(stgEagerBlackholeInfo)) : -(FUN_OFFSET(stgEagerBlackholeInfo)))];
char derivedConstantOFFSET_stgEagerBlackholeInfoSig[(intptr_t)(FUN_OFFSET(stgEagerBlackholeInfo)) >= 0 ? 3 : 1];
char derivedConstantOFFSET_stgGCEnter1Mag[1 + ((intptr_t)(FUN_OFFSET(stgGCEnter1)) >= 0 ? (FUN_OFFSET(stgGCEnter1)) : -(FUN_OFFSET(stgGCEnter1)))];
char derivedConstantOFFSET_stgGCEnter1Sig[(intptr_t)(FUN_OFFSET(stgGCEnter1)) >= 0 ? 3 : 1];
char derivedConstantOFFSET_stgGCFunMag[1 + ((intptr_t)(FUN_OFFSET(stgGCFun)) >= 0 ? (FUN_OFFSET(stgGCFun)) : -(FUN_OFFSET(stgGCFun)))];
char derivedConstantOFFSET_stgGCFunSig[(intptr_t)(FUN_OFFSET(stgGCFun)) >= 0 ? 3 : 1];
char derivedConstantOFFSET_Capability_r[1 + offsetof(Capability, r)];
char derivedConstantOFFSET_Capability_lock[1 + offsetof(Capability, lock)];
char derivedConstantOFFSET_Capability_no[1 + offsetof(Capability, no)];
char derivedConstantREP_Capability_no[1 + FIELD_SIZE(Capability, no)];
char derivedConstantOFFSET_Capability_mut_lists[1 + offsetof(Capability, mut_lists)];
char derivedConstantREP_Capability_mut_lists[1 + FIELD_SIZE(Capability, mut_lists)];
char derivedConstantOFFSET_Capability_context_switch[1 + offsetof(Capability, context_switch)];
char derivedConstantREP_Capability_context_switch[1 + FIELD_SIZE(Capability, context_switch)];
char derivedConstantOFFSET_Capability_interrupt[1 + offsetof(Capability, interrupt)];
char derivedConstantREP_Capability_interrupt[1 + FIELD_SIZE(Capability, interrupt)];
char derivedConstantOFFSET_Capability_sparks[1 + offsetof(Capability, sparks)];
char derivedConstantREP_Capability_sparks[1 + FIELD_SIZE(Capability, sparks)];
char derivedConstantOFFSET_bdescr_start[1 + offsetof(bdescr, start)];
char derivedConstantREP_bdescr_start[1 + FIELD_SIZE(bdescr, start)];
char derivedConstantOFFSET_bdescr_free[1 + offsetof(bdescr, free)];
char derivedConstantREP_bdescr_free[1 + FIELD_SIZE(bdescr, free)];
char derivedConstantOFFSET_bdescr_blocks[1 + offsetof(bdescr, blocks)];
char derivedConstantREP_bdescr_blocks[1 + FIELD_SIZE(bdescr, blocks)];
char derivedConstantOFFSET_bdescr_gen_no[1 + offsetof(bdescr, gen_no)];
char derivedConstantREP_bdescr_gen_no[1 + FIELD_SIZE(bdescr, gen_no)];
char derivedConstantOFFSET_bdescr_link[1 + offsetof(bdescr, link)];
char derivedConstantREP_bdescr_link[1 + FIELD_SIZE(bdescr, link)];
char derivedConstantSIZEOF_generation[1 + TYPE_SIZE(generation)];
char derivedConstantOFFSET_generation_n_new_large_words[1 + offsetof(generation, n_new_large_words)];
char derivedConstantREP_generation_n_new_large_words[1 + FIELD_SIZE(generation, n_new_large_words)];
char derivedConstantSIZEOF_CostCentreStack[1 + TYPE_SIZE(CostCentreStack)];
char derivedConstantOFFSET_CostCentreStack_ccsID[1 + offsetof(CostCentreStack, ccsID)];
char derivedConstantREP_CostCentreStack_ccsID[1 + FIELD_SIZE(CostCentreStack, ccsID)];
char derivedConstantOFFSET_CostCentreStack_mem_alloc[1 + offsetof(CostCentreStack, mem_alloc)];
char derivedConstantREP_CostCentreStack_mem_alloc[1 + FIELD_SIZE(CostCentreStack, mem_alloc)];
char derivedConstantOFFSET_CostCentreStack_scc_count[1 + offsetof(CostCentreStack, scc_count)];
char derivedConstantREP_CostCentreStack_scc_count[1 + FIELD_SIZE(CostCentreStack, scc_count)];
char derivedConstantOFFSET_CostCentreStack_prevStack[1 + offsetof(CostCentreStack, prevStack)];
char derivedConstantREP_CostCentreStack_prevStack[1 + FIELD_SIZE(CostCentreStack, prevStack)];
char derivedConstantOFFSET_CostCentre_ccID[1 + offsetof(CostCentre, ccID)];
char derivedConstantREP_CostCentre_ccID[1 + FIELD_SIZE(CostCentre, ccID)];
char derivedConstantOFFSET_CostCentre_link[1 + offsetof(CostCentre, link)];
char derivedConstantREP_CostCentre_link[1 + FIELD_SIZE(CostCentre, link)];
char derivedConstantOFFSET_StgHeader_info[1 + offsetof(StgHeader, info)];
char derivedConstantREP_StgHeader_info[1 + FIELD_SIZE(StgHeader, info)];
char derivedConstantOFFSET_StgHeader_ccs[1 + offsetof(StgHeader, prof.ccs)];
char derivedConstantREP_StgHeader_ccs[1 + FIELD_SIZE(StgHeader, prof.ccs)];
char derivedConstantOFFSET_StgHeader_ldvw[1 + offsetof(StgHeader, prof.hp.ldvw)];
char derivedConstantREP_StgHeader_ldvw[1 + FIELD_SIZE(StgHeader, prof.hp.ldvw)];
char derivedConstantSIZEOF_StgSMPThunkHeader[1 + TYPE_SIZE(StgSMPThunkHeader)];
char derivedConstantOFFSET_StgClosure_payload[1 + offsetof(StgClosure, payload) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgEntCounter_allocs[1 + offsetof(StgEntCounter, allocs)];
char derivedConstantREP_StgEntCounter_allocs[1 + FIELD_SIZE(StgEntCounter, allocs)];
char derivedConstantOFFSET_StgEntCounter_allocd[1 + offsetof(StgEntCounter, allocd)];
char derivedConstantREP_StgEntCounter_allocd[1 + FIELD_SIZE(StgEntCounter, allocd)];
char derivedConstantOFFSET_StgEntCounter_registeredp[1 + offsetof(StgEntCounter, registeredp)];
char derivedConstantREP_StgEntCounter_registeredp[1 + FIELD_SIZE(StgEntCounter, registeredp)];
char derivedConstantOFFSET_StgEntCounter_link[1 + offsetof(StgEntCounter, link)];
char derivedConstantREP_StgEntCounter_link[1 + FIELD_SIZE(StgEntCounter, link)];
char derivedConstantOFFSET_StgEntCounter_entry_count[1 + offsetof(StgEntCounter, entry_count)];
char derivedConstantREP_StgEntCounter_entry_count[1 + FIELD_SIZE(StgEntCounter, entry_count)];
char derivedConstantSIZEOF_StgUpdateFrame_NoHdr[1 + TYPE_SIZE(StgUpdateFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgUpdateFrame[1 + TYPE_SIZE(StgUpdateFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgCatchFrame_NoHdr[1 + TYPE_SIZE(StgCatchFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgCatchFrame[1 + TYPE_SIZE(StgCatchFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgStopFrame_NoHdr[1 + TYPE_SIZE(StgStopFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgStopFrame[1 + TYPE_SIZE(StgStopFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgMutArrPtrs_NoHdr[1 + TYPE_SIZE(StgMutArrPtrs) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgMutArrPtrs[1 + TYPE_SIZE(StgMutArrPtrs) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgMutArrPtrs_ptrs[1 + offsetof(StgMutArrPtrs, ptrs) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgMutArrPtrs_ptrs[1 + FIELD_SIZE(StgMutArrPtrs, ptrs)];
char derivedConstantOFFSET_StgMutArrPtrs_size[1 + offsetof(StgMutArrPtrs, size) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgMutArrPtrs_size[1 + FIELD_SIZE(StgMutArrPtrs, size)];
char derivedConstantSIZEOF_StgArrWords_NoHdr[1 + TYPE_SIZE(StgArrWords) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgArrWords[1 + TYPE_SIZE(StgArrWords) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgArrWords_bytes[1 + offsetof(StgArrWords, bytes) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgArrWords_bytes[1 + FIELD_SIZE(StgArrWords, bytes)];
char derivedConstantOFFSET_StgArrWords_payload[1 + offsetof(StgArrWords, payload) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgTSO__link[1 + offsetof(StgTSO, _link) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO__link[1 + FIELD_SIZE(StgTSO, _link)];
char derivedConstantOFFSET_StgTSO_global_link[1 + offsetof(StgTSO, global_link) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_global_link[1 + FIELD_SIZE(StgTSO, global_link)];
char derivedConstantOFFSET_StgTSO_what_next[1 + offsetof(StgTSO, what_next) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_what_next[1 + FIELD_SIZE(StgTSO, what_next)];
char derivedConstantOFFSET_StgTSO_why_blocked[1 + offsetof(StgTSO, why_blocked) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_why_blocked[1 + FIELD_SIZE(StgTSO, why_blocked)];
char derivedConstantOFFSET_StgTSO_block_info[1 + offsetof(StgTSO, block_info) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_block_info[1 + FIELD_SIZE(StgTSO, block_info)];
char derivedConstantOFFSET_StgTSO_blocked_exceptions[1 + offsetof(StgTSO, blocked_exceptions) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_blocked_exceptions[1 + FIELD_SIZE(StgTSO, blocked_exceptions)];
char derivedConstantOFFSET_StgTSO_id[1 + offsetof(StgTSO, id) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_id[1 + FIELD_SIZE(StgTSO, id)];
char derivedConstantOFFSET_StgTSO_cap[1 + offsetof(StgTSO, cap) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_cap[1 + FIELD_SIZE(StgTSO, cap)];
char derivedConstantOFFSET_StgTSO_saved_errno[1 + offsetof(StgTSO, saved_errno) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_saved_errno[1 + FIELD_SIZE(StgTSO, saved_errno)];
char derivedConstantOFFSET_StgTSO_trec[1 + offsetof(StgTSO, trec) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_trec[1 + FIELD_SIZE(StgTSO, trec)];
char derivedConstantOFFSET_StgTSO_flags[1 + offsetof(StgTSO, flags) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_flags[1 + FIELD_SIZE(StgTSO, flags)];
char derivedConstantOFFSET_StgTSO_dirty[1 + offsetof(StgTSO, dirty) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_dirty[1 + FIELD_SIZE(StgTSO, dirty)];
char derivedConstantOFFSET_StgTSO_bq[1 + offsetof(StgTSO, bq) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_bq[1 + FIELD_SIZE(StgTSO, bq)];
char derivedConstantOFFSET_StgTSO_cccs[1 + offsetof(StgTSO, prof.cccs) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_cccs[1 + FIELD_SIZE(StgTSO, prof.cccs)];
char derivedConstantOFFSET_StgTSO_stackobj[1 + offsetof(StgTSO, stackobj) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTSO_stackobj[1 + FIELD_SIZE(StgTSO, stackobj)];
char derivedConstantOFFSET_StgStack_sp[1 + offsetof(StgStack, sp) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgStack_sp[1 + FIELD_SIZE(StgStack, sp)];
char derivedConstantOFFSET_StgStack_stack[1 + offsetof(StgStack, stack) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgStack_stack_size[1 + offsetof(StgStack, stack_size) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgStack_stack_size[1 + FIELD_SIZE(StgStack, stack_size)];
char derivedConstantOFFSET_StgStack_dirty[1 + offsetof(StgStack, dirty) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgStack_dirty[1 + FIELD_SIZE(StgStack, dirty)];
char derivedConstantSIZEOF_StgTSOProfInfo[1 + TYPE_SIZE(StgTSOProfInfo)];
char derivedConstantOFFSET_StgUpdateFrame_updatee[1 + offsetof(StgUpdateFrame, updatee) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgUpdateFrame_updatee[1 + FIELD_SIZE(StgUpdateFrame, updatee)];
char derivedConstantOFFSET_StgCatchFrame_handler[1 + offsetof(StgCatchFrame, handler) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgCatchFrame_handler[1 + FIELD_SIZE(StgCatchFrame, handler)];
char derivedConstantOFFSET_StgCatchFrame_exceptions_blocked[1 + offsetof(StgCatchFrame, exceptions_blocked) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgCatchFrame_exceptions_blocked[1 + FIELD_SIZE(StgCatchFrame, exceptions_blocked)];
char derivedConstantSIZEOF_StgPAP_NoHdr[1 + TYPE_SIZE(StgPAP) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgPAP[1 + TYPE_SIZE(StgPAP) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgPAP_n_args[1 + offsetof(StgPAP, n_args) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgPAP_n_args[1 + FIELD_SIZE(StgPAP, n_args)];
char derivedConstantOFFSET_StgPAP_fun[1 + offsetof(StgPAP, fun) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgPAP_arity[1 + offsetof(StgPAP, arity) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgPAP_arity[1 + FIELD_SIZE(StgPAP, arity)];
char derivedConstantOFFSET_StgPAP_payload[1 + offsetof(StgPAP, payload) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgAP_NoThunkHdr[1 + TYPE_SIZE(StgAP) - TYPE_SIZE(StgThunkHeader)];
char derivedConstantSIZEOF_StgAP_NoHdr[1 + TYPE_SIZE(StgAP) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgAP[1 + TYPE_SIZE(StgAP) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgAP_n_args[1 + offsetof(StgAP, n_args) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgAP_n_args[1 + FIELD_SIZE(StgAP, n_args)];
char derivedConstantOFFSET_StgAP_fun[1 + offsetof(StgAP, fun) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgAP_payload[1 + offsetof(StgAP, payload) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgAP_STACK_NoThunkHdr[1 + TYPE_SIZE(StgAP_STACK) - TYPE_SIZE(StgThunkHeader)];
char derivedConstantSIZEOF_StgAP_STACK_NoHdr[1 + TYPE_SIZE(StgAP_STACK) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgAP_STACK[1 + TYPE_SIZE(StgAP_STACK) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgAP_STACK_size[1 + offsetof(StgAP_STACK, size) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgAP_STACK_size[1 + FIELD_SIZE(StgAP_STACK, size)];
char derivedConstantOFFSET_StgAP_STACK_fun[1 + offsetof(StgAP_STACK, fun) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgAP_STACK_payload[1 + offsetof(StgAP_STACK, payload) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgSelector_NoThunkHdr[1 + TYPE_SIZE(StgSelector) - TYPE_SIZE(StgThunkHeader)];
char derivedConstantSIZEOF_StgSelector_NoHdr[1 + TYPE_SIZE(StgSelector) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgSelector[1 + TYPE_SIZE(StgSelector) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgInd_indirectee[1 + offsetof(StgInd, indirectee) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgMutVar_NoHdr[1 + TYPE_SIZE(StgMutVar) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgMutVar[1 + TYPE_SIZE(StgMutVar) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgMutVar_var[1 + offsetof(StgMutVar, var) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgMutVar_var[1 + FIELD_SIZE(StgMutVar, var)];
char derivedConstantSIZEOF_StgAtomicallyFrame_NoHdr[1 + TYPE_SIZE(StgAtomicallyFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgAtomicallyFrame[1 + TYPE_SIZE(StgAtomicallyFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgAtomicallyFrame_code[1 + offsetof(StgAtomicallyFrame, code) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgAtomicallyFrame_code[1 + FIELD_SIZE(StgAtomicallyFrame, code)];
char derivedConstantOFFSET_StgAtomicallyFrame_next_invariant_to_check[1 + offsetof(StgAtomicallyFrame, next_invariant_to_check) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgAtomicallyFrame_next_invariant_to_check[1 + FIELD_SIZE(StgAtomicallyFrame, next_invariant_to_check)];
char derivedConstantOFFSET_StgAtomicallyFrame_result[1 + offsetof(StgAtomicallyFrame, result) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgAtomicallyFrame_result[1 + FIELD_SIZE(StgAtomicallyFrame, result)];
char derivedConstantOFFSET_StgInvariantCheckQueue_invariant[1 + offsetof(StgInvariantCheckQueue, invariant) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgInvariantCheckQueue_invariant[1 + FIELD_SIZE(StgInvariantCheckQueue, invariant)];
char derivedConstantOFFSET_StgInvariantCheckQueue_my_execution[1 + offsetof(StgInvariantCheckQueue, my_execution) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgInvariantCheckQueue_my_execution[1 + FIELD_SIZE(StgInvariantCheckQueue, my_execution)];
char derivedConstantOFFSET_StgInvariantCheckQueue_next_queue_entry[1 + offsetof(StgInvariantCheckQueue, next_queue_entry) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgInvariantCheckQueue_next_queue_entry[1 + FIELD_SIZE(StgInvariantCheckQueue, next_queue_entry)];
char derivedConstantOFFSET_StgAtomicInvariant_code[1 + offsetof(StgAtomicInvariant, code) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgAtomicInvariant_code[1 + FIELD_SIZE(StgAtomicInvariant, code)];
char derivedConstantOFFSET_StgTRecHeader_enclosing_trec[1 + offsetof(StgTRecHeader, enclosing_trec) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTRecHeader_enclosing_trec[1 + FIELD_SIZE(StgTRecHeader, enclosing_trec)];
char derivedConstantSIZEOF_StgCatchSTMFrame_NoHdr[1 + TYPE_SIZE(StgCatchSTMFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgCatchSTMFrame[1 + TYPE_SIZE(StgCatchSTMFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgCatchSTMFrame_handler[1 + offsetof(StgCatchSTMFrame, handler) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgCatchSTMFrame_handler[1 + FIELD_SIZE(StgCatchSTMFrame, handler)];
char derivedConstantOFFSET_StgCatchSTMFrame_code[1 + offsetof(StgCatchSTMFrame, code) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgCatchSTMFrame_code[1 + FIELD_SIZE(StgCatchSTMFrame, code)];
char derivedConstantSIZEOF_StgCatchRetryFrame_NoHdr[1 + TYPE_SIZE(StgCatchRetryFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgCatchRetryFrame[1 + TYPE_SIZE(StgCatchRetryFrame) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgCatchRetryFrame_running_alt_code[1 + offsetof(StgCatchRetryFrame, running_alt_code) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgCatchRetryFrame_running_alt_code[1 + FIELD_SIZE(StgCatchRetryFrame, running_alt_code)];
char derivedConstantOFFSET_StgCatchRetryFrame_first_code[1 + offsetof(StgCatchRetryFrame, first_code) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgCatchRetryFrame_first_code[1 + FIELD_SIZE(StgCatchRetryFrame, first_code)];
char derivedConstantOFFSET_StgCatchRetryFrame_alt_code[1 + offsetof(StgCatchRetryFrame, alt_code) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgCatchRetryFrame_alt_code[1 + FIELD_SIZE(StgCatchRetryFrame, alt_code)];
char derivedConstantOFFSET_StgTVarWatchQueue_closure[1 + offsetof(StgTVarWatchQueue, closure) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTVarWatchQueue_closure[1 + FIELD_SIZE(StgTVarWatchQueue, closure)];
char derivedConstantOFFSET_StgTVarWatchQueue_next_queue_entry[1 + offsetof(StgTVarWatchQueue, next_queue_entry) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTVarWatchQueue_next_queue_entry[1 + FIELD_SIZE(StgTVarWatchQueue, next_queue_entry)];
char derivedConstantOFFSET_StgTVarWatchQueue_prev_queue_entry[1 + offsetof(StgTVarWatchQueue, prev_queue_entry) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTVarWatchQueue_prev_queue_entry[1 + FIELD_SIZE(StgTVarWatchQueue, prev_queue_entry)];
char derivedConstantSIZEOF_StgTVar_NoHdr[1 + TYPE_SIZE(StgTVar) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgTVar[1 + TYPE_SIZE(StgTVar) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgTVar_current_value[1 + offsetof(StgTVar, current_value) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTVar_current_value[1 + FIELD_SIZE(StgTVar, current_value)];
char derivedConstantOFFSET_StgTVar_first_watch_queue_entry[1 + offsetof(StgTVar, first_watch_queue_entry) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTVar_first_watch_queue_entry[1 + FIELD_SIZE(StgTVar, first_watch_queue_entry)];
char derivedConstantOFFSET_StgTVar_num_updates[1 + offsetof(StgTVar, num_updates) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgTVar_num_updates[1 + FIELD_SIZE(StgTVar, num_updates)];
char derivedConstantSIZEOF_StgWeak_NoHdr[1 + TYPE_SIZE(StgWeak) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgWeak[1 + TYPE_SIZE(StgWeak) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgWeak_link[1 + offsetof(StgWeak, link) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgWeak_link[1 + FIELD_SIZE(StgWeak, link)];
char derivedConstantOFFSET_StgWeak_key[1 + offsetof(StgWeak, key) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgWeak_key[1 + FIELD_SIZE(StgWeak, key)];
char derivedConstantOFFSET_StgWeak_value[1 + offsetof(StgWeak, value) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgWeak_value[1 + FIELD_SIZE(StgWeak, value)];
char derivedConstantOFFSET_StgWeak_finalizer[1 + offsetof(StgWeak, finalizer) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgWeak_finalizer[1 + FIELD_SIZE(StgWeak, finalizer)];
char derivedConstantOFFSET_StgWeak_cfinalizer[1 + offsetof(StgWeak, cfinalizer) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgWeak_cfinalizer[1 + FIELD_SIZE(StgWeak, cfinalizer)];
char derivedConstantSIZEOF_StgDeadWeak_NoHdr[1 + TYPE_SIZE(StgDeadWeak) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgDeadWeak[1 + TYPE_SIZE(StgDeadWeak) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgDeadWeak_link[1 + offsetof(StgDeadWeak, link) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgDeadWeak_link[1 + FIELD_SIZE(StgDeadWeak, link)];
char derivedConstantSIZEOF_StgMVar_NoHdr[1 + TYPE_SIZE(StgMVar) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgMVar[1 + TYPE_SIZE(StgMVar) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgMVar_head[1 + offsetof(StgMVar, head) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgMVar_head[1 + FIELD_SIZE(StgMVar, head)];
char derivedConstantOFFSET_StgMVar_tail[1 + offsetof(StgMVar, tail) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgMVar_tail[1 + FIELD_SIZE(StgMVar, tail)];
char derivedConstantOFFSET_StgMVar_value[1 + offsetof(StgMVar, value) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgMVar_value[1 + FIELD_SIZE(StgMVar, value)];
char derivedConstantSIZEOF_StgMVarTSOQueue_NoHdr[1 + TYPE_SIZE(StgMVarTSOQueue) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgMVarTSOQueue[1 + TYPE_SIZE(StgMVarTSOQueue) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgMVarTSOQueue_link[1 + offsetof(StgMVarTSOQueue, link) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgMVarTSOQueue_link[1 + FIELD_SIZE(StgMVarTSOQueue, link)];
char derivedConstantOFFSET_StgMVarTSOQueue_tso[1 + offsetof(StgMVarTSOQueue, tso) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgMVarTSOQueue_tso[1 + FIELD_SIZE(StgMVarTSOQueue, tso)];
char derivedConstantSIZEOF_StgBCO_NoHdr[1 + TYPE_SIZE(StgBCO) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgBCO[1 + TYPE_SIZE(StgBCO) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgBCO_instrs[1 + offsetof(StgBCO, instrs) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBCO_instrs[1 + FIELD_SIZE(StgBCO, instrs)];
char derivedConstantOFFSET_StgBCO_literals[1 + offsetof(StgBCO, literals) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBCO_literals[1 + FIELD_SIZE(StgBCO, literals)];
char derivedConstantOFFSET_StgBCO_ptrs[1 + offsetof(StgBCO, ptrs) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBCO_ptrs[1 + FIELD_SIZE(StgBCO, ptrs)];
char derivedConstantOFFSET_StgBCO_arity[1 + offsetof(StgBCO, arity) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBCO_arity[1 + FIELD_SIZE(StgBCO, arity)];
char derivedConstantOFFSET_StgBCO_size[1 + offsetof(StgBCO, size) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBCO_size[1 + FIELD_SIZE(StgBCO, size)];
char derivedConstantOFFSET_StgBCO_bitmap[1 + offsetof(StgBCO, bitmap) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgStableName_NoHdr[1 + TYPE_SIZE(StgStableName) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgStableName[1 + TYPE_SIZE(StgStableName) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgStableName_sn[1 + offsetof(StgStableName, sn) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgStableName_sn[1 + FIELD_SIZE(StgStableName, sn)];
char derivedConstantSIZEOF_StgBlockingQueue_NoHdr[1 + TYPE_SIZE(StgBlockingQueue) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_StgBlockingQueue[1 + TYPE_SIZE(StgBlockingQueue) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_StgBlockingQueue_bh[1 + offsetof(StgBlockingQueue, bh) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBlockingQueue_bh[1 + FIELD_SIZE(StgBlockingQueue, bh)];
char derivedConstantOFFSET_StgBlockingQueue_owner[1 + offsetof(StgBlockingQueue, owner) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBlockingQueue_owner[1 + FIELD_SIZE(StgBlockingQueue, owner)];
char derivedConstantOFFSET_StgBlockingQueue_queue[1 + offsetof(StgBlockingQueue, queue) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBlockingQueue_queue[1 + FIELD_SIZE(StgBlockingQueue, queue)];
char derivedConstantOFFSET_StgBlockingQueue_link[1 + offsetof(StgBlockingQueue, link) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_StgBlockingQueue_link[1 + FIELD_SIZE(StgBlockingQueue, link)];
char derivedConstantSIZEOF_MessageBlackHole_NoHdr[1 + TYPE_SIZE(MessageBlackHole) - TYPE_SIZE(StgHeader)];
char derivedConstantSIZEOF_MessageBlackHole[1 + TYPE_SIZE(MessageBlackHole) - TYPE_SIZE(StgHeader)];
char derivedConstantOFFSET_MessageBlackHole_link[1 + offsetof(MessageBlackHole, link) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_MessageBlackHole_link[1 + FIELD_SIZE(MessageBlackHole, link)];
char derivedConstantOFFSET_MessageBlackHole_tso[1 + offsetof(MessageBlackHole, tso) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_MessageBlackHole_tso[1 + FIELD_SIZE(MessageBlackHole, tso)];
char derivedConstantOFFSET_MessageBlackHole_bh[1 + offsetof(MessageBlackHole, bh) - TYPE_SIZE(StgHeader)];
char derivedConstantREP_MessageBlackHole_bh[1 + FIELD_SIZE(MessageBlackHole, bh)];
char derivedConstantOFFSET_RtsFlags_ProfFlags_showCCSOnException[1 + offsetof(RTS_FLAGS, ProfFlags.showCCSOnException)];
char derivedConstantREP_RtsFlags_ProfFlags_showCCSOnException[1 + FIELD_SIZE(RTS_FLAGS, ProfFlags.showCCSOnException)];
char derivedConstantOFFSET_RtsFlags_DebugFlags_apply[1 + offsetof(RTS_FLAGS, DebugFlags.apply)];
char derivedConstantREP_RtsFlags_DebugFlags_apply[1 + FIELD_SIZE(RTS_FLAGS, DebugFlags.apply)];
char derivedConstantOFFSET_RtsFlags_DebugFlags_sanity[1 + offsetof(RTS_FLAGS, DebugFlags.sanity)];
char derivedConstantREP_RtsFlags_DebugFlags_sanity[1 + FIELD_SIZE(RTS_FLAGS, DebugFlags.sanity)];
char derivedConstantOFFSET_RtsFlags_DebugFlags_weak[1 + offsetof(RTS_FLAGS, DebugFlags.weak)];
char derivedConstantREP_RtsFlags_DebugFlags_weak[1 + FIELD_SIZE(RTS_FLAGS, DebugFlags.weak)];
char derivedConstantOFFSET_RtsFlags_GcFlags_initialStkSize[1 + offsetof(RTS_FLAGS, GcFlags.initialStkSize)];
char derivedConstantREP_RtsFlags_GcFlags_initialStkSize[1 + FIELD_SIZE(RTS_FLAGS, GcFlags.initialStkSize)];
char derivedConstantOFFSET_RtsFlags_MiscFlags_tickInterval[1 + offsetof(RTS_FLAGS, MiscFlags.tickInterval)];
char derivedConstantREP_RtsFlags_MiscFlags_tickInterval[1 + FIELD_SIZE(RTS_FLAGS, MiscFlags.tickInterval)];
char derivedConstantSIZEOF_StgFunInfoExtraFwd[1 + TYPE_SIZE(StgFunInfoExtraFwd)];
char derivedConstantOFFSET_StgFunInfoExtraFwd_slow_apply[1 + offsetof(StgFunInfoExtraFwd, slow_apply)];
char derivedConstantREP_StgFunInfoExtraFwd_slow_apply[1 + FIELD_SIZE(StgFunInfoExtraFwd, slow_apply)];
char derivedConstantOFFSET_StgFunInfoExtraFwd_fun_type[1 + offsetof(StgFunInfoExtraFwd, fun_type)];
char derivedConstantREP_StgFunInfoExtraFwd_fun_type[1 + FIELD_SIZE(StgFunInfoExtraFwd, fun_type)];
char derivedConstantOFFSET_StgFunInfoExtraFwd_arity[1 + offsetof(StgFunInfoExtraFwd, arity)];
char derivedConstantREP_StgFunInfoExtraFwd_arity[1 + FIELD_SIZE(StgFunInfoExtraFwd, arity)];
char derivedConstantOFFSET_StgFunInfoExtraFwd_bitmap[1 + offsetof(StgFunInfoExtraFwd, b.bitmap)];
char derivedConstantREP_StgFunInfoExtraFwd_bitmap[1 + FIELD_SIZE(StgFunInfoExtraFwd, b.bitmap)];
char derivedConstantSIZEOF_StgFunInfoExtraRev[1 + TYPE_SIZE(StgFunInfoExtraRev)];
char derivedConstantOFFSET_StgFunInfoExtraRev_slow_apply_offset[1 + offsetof(StgFunInfoExtraRev, slow_apply_offset)];
char derivedConstantREP_StgFunInfoExtraRev_slow_apply_offset[1 + FIELD_SIZE(StgFunInfoExtraRev, slow_apply_offset)];
char derivedConstantOFFSET_StgFunInfoExtraRev_fun_type[1 + offsetof(StgFunInfoExtraRev, fun_type)];
char derivedConstantREP_StgFunInfoExtraRev_fun_type[1 + FIELD_SIZE(StgFunInfoExtraRev, fun_type)];
char derivedConstantOFFSET_StgFunInfoExtraRev_arity[1 + offsetof(StgFunInfoExtraRev, arity)];
char derivedConstantREP_StgFunInfoExtraRev_arity[1 + FIELD_SIZE(StgFunInfoExtraRev, arity)];
char derivedConstantOFFSET_StgFunInfoExtraRev_bitmap[1 + offsetof(StgFunInfoExtraRev, b.bitmap)];
char derivedConstantREP_StgFunInfoExtraRev_bitmap[1 + FIELD_SIZE(StgFunInfoExtraRev, b.bitmap)];
char derivedConstantOFFSET_StgLargeBitmap_size[1 + offsetof(StgLargeBitmap, size)];
char derivedConstantREP_StgLargeBitmap_size[1 + FIELD_SIZE(StgLargeBitmap, size)];
char derivedConstantOFFSET_StgLargeBitmap_bitmap[1 + offsetof(StgLargeBitmap, bitmap)];
char derivedConstantSIZEOF_snEntry[1 + TYPE_SIZE(snEntry)];
char derivedConstantOFFSET_snEntry_sn_obj[1 + offsetof(snEntry, sn_obj)];
char derivedConstantREP_snEntry_sn_obj[1 + FIELD_SIZE(snEntry, sn_obj)];
char derivedConstantOFFSET_snEntry_addr[1 + offsetof(snEntry, addr)];
char derivedConstantREP_snEntry_addr[1 + FIELD_SIZE(snEntry, addr)];
char derivedConstantSIZEOF_spEntry[1 + TYPE_SIZE(spEntry)];
char derivedConstantOFFSET_spEntry_addr[1 + offsetof(spEntry, addr)];
char derivedConstantREP_spEntry_addr[1 + FIELD_SIZE(spEntry, addr)];
char derivedConstantMAX_SPEC_SELECTEE_SIZE[1 + MAX_SPEC_SELECTEE_SIZE];
char derivedConstantMAX_SPEC_AP_SIZE[1 + MAX_SPEC_AP_SIZE];
char derivedConstantMIN_PAYLOAD_SIZE[1 + MIN_PAYLOAD_SIZE];
char derivedConstantMIN_INTLIKEMag[1 + ((intptr_t)(MIN_INTLIKE) >= 0 ? (MIN_INTLIKE) : -(MIN_INTLIKE))];
char derivedConstantMIN_INTLIKESig[(intptr_t)(MIN_INTLIKE) >= 0 ? 3 : 1];
char derivedConstantMAX_INTLIKE[1 + MAX_INTLIKE];
char derivedConstantMIN_CHARLIKE[1 + MIN_CHARLIKE];
char derivedConstantMAX_CHARLIKE[1 + MAX_CHARLIKE];
char derivedConstantMUT_ARR_PTRS_CARD_BITS[1 + MUT_ARR_PTRS_CARD_BITS];
char derivedConstantMAX_Vanilla_REG[1 + MAX_VANILLA_REG];
char derivedConstantMAX_Float_REG[1 + MAX_FLOAT_REG];
char derivedConstantMAX_Double_REG[1 + MAX_DOUBLE_REG];
char derivedConstantMAX_Long_REG[1 + MAX_LONG_REG];
char derivedConstantMAX_SSE_REG[1 + MAX_SSE_REG];
char derivedConstantMAX_Real_Vanilla_REG[1 + MAX_REAL_VANILLA_REG];
char derivedConstantMAX_Real_Float_REG[1 + MAX_REAL_FLOAT_REG];
char derivedConstantMAX_Real_Double_REG[1 + MAX_REAL_DOUBLE_REG];
char derivedConstantMAX_Real_SSE_REG[1 + MAX_REAL_SSE_REG];
char derivedConstantMAX_Real_Long_REG[1 + MAX_REAL_LONG_REG];
char derivedConstantRESERVED_C_STACK_BYTES[1 + RESERVED_C_STACK_BYTES];
char derivedConstantRESERVED_STACK_WORDS[1 + RESERVED_STACK_WORDS];
char derivedConstantAP_STACK_SPLIM[1 + AP_STACK_SPLIM];
char derivedConstantWORD_SIZE[1 + SIZEOF_HSWORD];
char derivedConstantDOUBLE_SIZE[1 + SIZEOF_DOUBLE];
char derivedConstantCINT_SIZE[1 + SIZEOF_INT];
char derivedConstantCLONG_SIZE[1 + SIZEOF_LONG];
char derivedConstantCLONG_LONG_SIZE[1 + SIZEOF_LONG_LONG];
char derivedConstantBITMAP_BITS_SHIFT[1 + BITMAP_BITS_SHIFT];
char derivedConstantTAG_BITS[1 + TAG_BITS];
#if defined(WORDS_BIGENDIAN)
char derivedConstantWORDS_BIGENDIAN[1];
#else
char derivedConstantWORDS_BIGENDIAN[2];
#endif
#if defined(DYNAMIC_BY_DEFAULT)
char derivedConstantDYNAMIC_BY_DEFAULT[1];
#else
char derivedConstantDYNAMIC_BY_DEFAULT[2];
#endif
char derivedConstantLDV_SHIFT[1 + LDV_SHIFT];
char derivedConstantILDV_CREATE_MASK0[1 + (((uint64_t)(size_t)(LDV_CREATE_MASK)) & 0xFFFF)];
char derivedConstantILDV_CREATE_MASK1[1 + ((((uint64_t)(size_t)(LDV_CREATE_MASK)) >> 16) & 0xFFFF)];
char derivedConstantILDV_CREATE_MASK2[1 + ((((uint64_t)(size_t)(LDV_CREATE_MASK)) >> 32) & 0xFFFF)];
char derivedConstantILDV_CREATE_MASK3[1 + ((((uint64_t)(size_t)(LDV_CREATE_MASK)) >> 48) & 0xFFFF)];
char derivedConstantILDV_STATE_CREATE0[1 + (((uint64_t)(size_t)(LDV_STATE_CREATE)) & 0xFFFF)];
char derivedConstantILDV_STATE_CREATE1[1 + ((((uint64_t)(size_t)(LDV_STATE_CREATE)) >> 16) & 0xFFFF)];
char derivedConstantILDV_STATE_CREATE2[1 + ((((uint64_t)(size_t)(LDV_STATE_CREATE)) >> 32) & 0xFFFF)];
char derivedConstantILDV_STATE_CREATE3[1 + ((((uint64_t)(size_t)(LDV_STATE_CREATE)) >> 48) & 0xFFFF)];
char derivedConstantILDV_STATE_USE0[1 + (((uint64_t)(size_t)(LDV_STATE_USE)) & 0xFFFF)];
char derivedConstantILDV_STATE_USE1[1 + ((((uint64_t)(size_t)(LDV_STATE_USE)) >> 16) & 0xFFFF)];
char derivedConstantILDV_STATE_USE2[1 + ((((uint64_t)(size_t)(LDV_STATE_USE)) >> 32) & 0xFFFF)];
char derivedConstantILDV_STATE_USE3[1 + ((((uint64_t)(size_t)(LDV_STATE_USE)) >> 48) & 0xFFFF)];
